workflows:
  android-aab:
    name: Build AAB
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      groups:
        - google_play
      vars:
        XCODE_WORKSPACE: ""
      node: 20.11.1
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm install || yarn install
      - name: Build Android AAB
        script: |
          cd android
          chmod +x gradlew
          ./gradlew bundleRelease
    artifacts:
      - android/app/build/outputs/bundle/release/*.aab
      - android/app/build/outputs/**/*.aab
