name: Build AAB - New
on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get your AAB
        run: |
          unzip -o "Woi 1.0.zip" -d ./src
          ls -la ./src/android/
          echo "AAB found at:"
          find ./src -name "*.aab" -type f
      - uses: actions/upload-artifact@v4
        with:
          name: your-aab-ready-for-playstore
          path: ./src/android/app-release.aab
